version: "3"

tasks:
  compile:
    # method: timestamp
    sources:
      - src/**/*.ts
    generates:
      - dist/**/*.js
    cmds:
      - npx tsc -d --sourcemap

  tapx:
    deps: [compile]
    cmds:
      - npx tap -t600 --disable-coverage --reporter=terse {{.CLI_ARGS}}
