version: "3"

tasks:
  compile:
    # method: timestamp
    sources:
      - src/**/*.ts
    generates:
      - dist/**/*.js
    cmds:
      - npx tsc -d --sourcemap

  tapx:
    deps: [compile]
    cmds:
      - npx tap -t600 --disable-coverage --reporter=terse {{.CLI_ARGS}}

  c8test:
    method: none
    deps: [compile]
    cmds:
      - c8 npx tap -t600 --disable-coverage --reporter=terse 'tests/**/*.tap.*js'

  c8html:
    method: none
    deps: [c8test]
    cmds:
      - c8 report -r html
